
export const FETCHING_PRODUCT="FETCHING_PRODUCT";
export const ADD_COURSE="ADD_COURSE";
export const DROP_COURSE="DROP_COURSE";
export const GET_ROLE="GET_ROLE";
export const FETCHING_CLASS_TO_JOIN='FETCHING_CLASS_TO_JOIN';